# Generated by Django 5.1.3 on 2024-11-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=200)),
                ('comarca', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Arquivado', 'Arquivado')], max_length=50)),
            ],
        ),
    ]
