# Generated by Django 5.1.3 on 2024-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('Fisica', 'Física'), ('Juridica', 'Jurídica')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
