# Generated by Django 5.1.3 on 2024-11-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pessoa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_conclusao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('pessoas', models.ManyToManyField(related_name='tasks', to='users.pessoa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.processo')),
            ],
        ),
    ]
