# Generated by Django 5.1.3 on 2024-11-28 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
