# Generated by Django 5.1.3 on 2024-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_task_criado_em_task_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='valor_advogado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='valor_total_processo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
