# Generated by Django 5.1.3 on 2024-11-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_task_valor_advogado_task_valor_total_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
