# Generated by Django 5.1.3 on 2024-11-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_document_code_remove_document_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('Credito', 'Crédito'), ('Debito', 'Débito')], max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('conta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='users.pessoa')),
            ],
        ),
    ]
