# Generated by Django 5.1.3 on 2024-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
