# Generated by Django 5.1.3 on 2024-11-30 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_pagamento_pessoa_pagamento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='codigo',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
    ]
