# Generated by Django 5.1.3 on 2024-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_pagamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
