# Generated by Django 5.1.3 on 2024-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_pagamento_nome_alter_pagamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
    ]
