# Generated by Django 5.1.3 on 2024-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pagamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, default='pessoas_fotos/default.jpg', null=True, upload_to='pessoas_fotos/'),
        ),
    ]
